app-config:
  apikey: 7d994852-218a-4e05-b50a-f7cff7301f1d
  jwt:
    expiration: 180000
    secret: eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJBcGkgZG8gRm9ydW0gZGEgQWx1cmEiLCJzdWIiOiIxIiwiaWF0IjoxNjMzMzAxNjc1LCJleHAiOjE2MzMzMDE2ODR9

spring:
  application:
    name: "@project.name@"
  jpa:
    open-in-view: false
  profiles:
    active: ${APP_PROFILE:dev}

